# Common
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias less='less -r'
alias tmp='cd /tmp'

# others
alias vi='vim'
alias sim='sudo vim'
alias ..="cd .."
alias vi='vim'

alias ls='ls $LS_OPTIONS -Fh'
alias ll='ls $LS_OPTIONS -Fhl'
alias la='ll $LS_OPTIONS -FhlA'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# tmux
alias tmux='tmux -2'

# python
alias activate='source .env/bin/activate'
