# $HOME/.bashrc for bash-3.0 (or later)

# if not running interactively, don't do anything
[ -z "$PS1"  ] && return

__command () {
    command -v $1 1>/dev/null
}

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
# Use move to trash instead of remove
rm="mv -t ~/.Trash"


# Alias definitions
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.bash_functions ]; then
    . ~/.bash_functions
fi

export DEBFULLNAME="__BASH_DEBFULLNAME__"
export DEBEMAIL="__BASH_DEBEMAIL__"
export USERNAME="__BASH_USERNAME__"
export EMAIL="__BASH_EMAIL__"
export HISTTIMEFORMAT="%h/%d - %H:%M:%S "
export LANG="en_US.UTF-8"

export GOPATH=$HOME/go

# AWS credentials
export EC2_PRIVATE_KEY=$(echo $HOME/.keys/ec2/pk-*.pem)
export EC2_CERT=$(echo $HOME/.keys/ec2/cert-*.pem)
export AWS_CREDENTIAL_FILE=$HOME/.keys/ec2/aws-credential-file.txt

# color ls
# if [ "$TERM" != "dumb" ]; then
#     export LS_OPTIONS='--color=auto --group-directories-first'
#     eval `dircolors -b $HOME/.dir_colors`
# fi

function have() {
    return $( which $1 >/dev/null )
}

setup () {
    local SRCDIR=$HOME/.home
    local CFGDIR=$SRCDIR/config

    local INCDIR=$CFGDIR/bash/include
    local CMPDIR=$CFGDIR/bash/completion

    # Completion
    source $INCDIR/colors.sh
    source $INCDIR/ps.sh
    source $INCDIR/git.sh

    source $CMPDIR/vagrant-completion.bash

    # Close promt
    PS1="${debian_chroot:+($debian_chroot)}${PS1}\n$ "
}

setup && unset setup

# Completion
# source $HOME/.home/config/bash/completion/*-completion.bash
# source $HOME/.home/config/bash/completion/ack-grep-completion.bash
# source $HOME/.home/config/bash/completion/ag-completion.bash
# source $HOME/.home/config/bash/completion/django-completion.bash
# source $HOME/.home/config/bash/completion/gem1.9.1-completion.bash
# source $HOME/.home/config/bash/completion/git-buildpackage-completion.bash
# source $HOME/.home/config/bash/completion/git-completion.bash
# source $HOME/.home/config/bash/completion/git-flow-completion.bash
# source $HOME/.home/config/bash/completion/mercurial-completion.bash
# source $HOME/.home/config/bash/completion/openvpn-completion.bash
# source $HOME/.home/config/bash/completion/pip-completion.bash
# source $HOME/.home/config/bash/completion/vagrant-completion.bash
# source $HOME/.home/config/bash/completion/virtualenv-completion.bash

# load anaconda
export PATH=~/anaconda/bin:$PATH

# Tmux fix vim color
TERM=screen-256color
